# global constants available to the app
# last update:2016-10-08

# constants required for every app
appName <- 'room'
appTitle <- 'Raumklima'
app_id <- 'eu.ownyourdata.room'
scheduler_id <- 'eu.ownyourdata.scheduler'        

# definition of data structure
currRepoSelect <- ''
appRepos <- list()
appReposDefault <- list(Nagios   = 'eu.ownyourdata.room.nagios',
                        Actuator = 'eu.ownyourdata.room.actuator',
                        Verlauf  = 'eu.ownyourdata.room.log')
appStruct <- list(
        Nagios = list(
                fields      = c('name', 'nagiosUrl', 'repo', 'user', 'password', 'active'),
                fieldKey    = 'name',
                fieldTypes  = c('string', 'string', 'string', 'string', 'string', 'boolean'),
                fieldInits  = c('empty', 'empty', 'empty', 'empty', 'empty', 'false'),
                fieldTitles = c('Sensor', 'NAGIOS URL', 'Repo', 'Benutzer', 'Passwort', 'aktiv'),
                fieldWidths = c(150, 200, 150, 100, 100, 60)),
        Actuator = list(
                fields      = c('name', 'scenarios', 'params', 'command', 'active'),
                fieldKey    = 'name',
                fieldTypes  = c('string', 'string', 'string', 'string', 'boolean'),
                fieldInits  = c('empty', 'empty', 'empty', 'empty', 'false'),
                fieldTitles = c('Aktor', 'Szenario', 'Parameter', 'Befehl', 'aktiv'),
                fieldWidths = c(150, 150, 250, 100, 60)),
        Verlauf = list(
                fields      = c('date', 'description'),
                fieldKey    = 'date',
                fieldTypes  = c('date', 'string'),
                fieldInits  = c('empty', 'empty'),
                fieldTitles = c('Datum', 'Text'),
                fieldWidths = c(150, 450)))

# appFields <- c('timestamp', 'value')
# appFieldKey <- 'timestamp'
# appFieldTypes <- c('timestamp', 'number')
# appFieldInits <- c('empty', 'empty')
# appFieldTitles <- c('Zeit', 'Wert')
# appFieldWidths <- c(100, 100)

# Version information
currVersion <- "0.3.1"
verHistory <- data.frame(rbind(
        c(version = "0.3.1",
          text    = "Verwendung von Listennamen in neuem Datentresor"),
        c(version = "0.3.0",
          text    = "erstes Release")
))

# app specific constants
sensorUiList <- vector()
actuatorUiList <- c('Dienstagabend')

scriptRepo <- 'eu.ownyourdata.room.script'
nagiosImportScript <- 'ZGVmYXVsdEhlYWRlcnMgPC0gZnVuY3Rpb24odG9rZW4pIHsNCiAgYygnQWNjZXB0JyAgICAgICAgPSAnKi8qJywgJ0NvbnRlbnQtVHlwZScgID0gJ2FwcGxpY2F0aW9uL2pzb24nLCAnQXV0aG9yaXphdGlvbicgPSBwYXN0ZSgnQmVhcmVyJywgdG9rZW4pKQ0KfQ0KaXRlbXNVcmwgPC0gZnVuY3Rpb24odXJsLCByZXBvX25hbWUpIHsNCiAgcGFzdGUwKHVybCwgJy9hcGkvcmVwb3MvJywgcmVwb19uYW1lLCAnL2l0ZW1zJykNCn0NCmdldFRva2VuIDwtIGZ1bmN0aW9uKHBpYV91cmwsIGFwcF9rZXksIGFwcF9zZWNyZXQpIHsNCiAgYXV0aF91cmwgPC0gcGFzdGUwKHBpYV91cmwsICcvb2F1dGgvdG9rZW4nKQ0KICBvcHRUaW1lb3V0IDwtIFJDdXJsOjpjdXJsT3B0aW9ucyhjb25uZWN0dGltZW91dCA9IDEwKQ0KICByZXNwb25zZSA8LSB0cnlDYXRjaCgNCiAgICBSQ3VybDo6cG9zdEZvcm0oYXV0aF91cmwsIGNsaWVudF9pZCA9IGFwcF9rZXksIGNsaWVudF9zZWNyZXQgPSBhcHBfc2VjcmV0LCBncmFudF90eXBlID0gJ2NsaWVudF9jcmVkZW50aWFscycsIC5vcHRzID0gb3B0VGltZW91dCksDQogICAgZXJyb3IgPSBmdW5jdGlvbihlKSB7IHJldHVybihOQSkgfSkNCiAgaWYgKGlzLm5hKHJlc3BvbnNlKSkgew0KICAgIHJldHVybihOQSkNCiAgfSBlbHNlIHsNCiAgICBpZihqc29ubGl0ZTo6dmFsaWRhdGUocmVzcG9uc2VbMV0pKXsNCiAgICAgIHJldHVybihyanNvbjo6ZnJvbUpTT04ocmVzcG9uc2VbMV0pJGFjY2Vzc190b2tlbikNCiAgICB9IGVsc2Ugew0KICAgICAgcmV0dXJuKE5BKQ0KICAgIH0NCiAgfQ0KfQ0Kc2V0dXBBcHAgPC0gZnVuY3Rpb24ocGlhX3VybCwgYXBwX2tleSwgYXBwX3NlY3JldCkgew0KICBhcHBfdG9rZW4gPC0gZ2V0VG9rZW4ocGlhX3VybCwgYXBwX2tleSwgYXBwX3NlY3JldCkNCiAgaWYoaXMubmEoYXBwX3Rva2VuKSl7DQogICAgdmVjdG9yKCkNCiAgfSBlbHNlIHsNCiAgICBjKCd1cmwnID0gcGlhX3VybCwgJ2FwcF9rZXknID0gYXBwX2tleSwgJ2FwcF9zZWNyZXQnID0gYXBwX3NlY3JldCwgJ3Rva2VuJyA9IGFwcF90b2tlbikNCiAgfQ0KfQ0KcjJkIDwtIGZ1bmN0aW9uKHJlc3BvbnNlKXsNCiAgaWYgKGlzLm5hKHJlc3BvbnNlKSkgew0KICAgIGRhdGEuZnJhbWUoKQ0KICB9IGVsc2Ugew0KICAgIGlmIChuY2hhcihyZXNwb25zZSkgPiAwKSB7DQogICAgICByZXRWYWwgPC0gcmpzb246OmZyb21KU09OKHJlc3BvbnNlKQ0KICAgICAgaWYobGVuZ3RoKHJldFZhbCkgPT0gMCkgew0KICAgICAgICBkYXRhLmZyYW1lKCkNCiAgICAgIH0gZWxzZSB7DQogICAgICAgIGlmICgnZXJyb3InICVpbiUgbmFtZXMocmV0VmFsKSkgew0KICAgICAgICAgIGRhdGEuZnJhbWUoKQ0KICAgICAgICB9IGVsc2Ugew0KICAgICAgICAgIGlmICghaXMubnVsbChyZXRWYWwkbWVzc2FnZSkpIHsNCiAgICAgICAgICAgIGlmIChyZXRWYWwkbWVzc2FnZSA9PSANCiAgICAgICAgICAgICAgICAnZXJyb3IuYWNjZXNzRGVuaWVkJykgew0KICAgICAgICAgICAgICBkYXRhLmZyYW1lKCkNCiAgICAgICAgICAgIH0gZWxzZSB7DQogICAgICAgICAgICAgIGRvLmNhbGwocmJpbmQsIGxhcHBseShyZXRWYWwsIGRhdGEuZnJhbWUpKQ0KICAgICAgICAgICAgfQ0KICAgICAgICAgIH0gZWxzZSB7DQogICAgICAgICAgICBkby5jYWxsKHJiaW5kLCBsYXBwbHkocmV0VmFsLCBkYXRhLmZyYW1lKSkNCiAgICAgICAgICB9DQogICAgICAgIH0NCiAgICAgIH0NCiAgICB9IGVsc2Ugew0KICAgICAgZGF0YS5mcmFtZSgpDQogICAgfQ0KICB9DQp9DQpyZWFkSXRlbXMgPC0gZnVuY3Rpb24oYXBwLCByZXBvX3VybCkgew0KICBpZiAobGVuZ3RoKGFwcCkgPT0gMCkgew0KICAgIGRhdGEuZnJhbWUoKQ0KICAgIHJldHVybigpDQogIH0NCiAgaGVhZGVycyA8LSBkZWZhdWx0SGVhZGVycyhhcHBbWyd0b2tlbiddXSkNCiAgdXJsX2RhdGEgPC0gcGFzdGUwKHJlcG9fdXJsLCAnP3NpemU9MjAwMCcpDQogIGhlYWRlciA8LSBSQ3VybDo6YmFzaWNIZWFkZXJHYXRoZXJlcigpDQogIGRvYyA8LSB0cnlDYXRjaCgNCiAgICBSQ3VybDo6Z2V0VVJJKHVybF9kYXRhLCAub3B0cz1saXN0KGh0dHBoZWFkZXIgPSBoZWFkZXJzKSwgaGVhZGVyZnVuY3Rpb24gPSBoZWFkZXIkdXBkYXRlKSwNCiAgICBlcnJvciA9IGZ1bmN0aW9uKGUpIHsgcmV0dXJuKE5BKSB9KQ0KICByZXNwb25zZSA8LSBOQQ0KICByZXNwRGF0YSA8LSBkYXRhLmZyYW1lKCkNCiAgaWYoIWlzLm5hKGRvYykpew0KICAgIHJlY3MgPC0gdHJ5Q2F0Y2goDQogICAgICBhcy5pbnRlZ2VyKGhlYWRlciR2YWx1ZSgpW1snWC1Ub3RhbC1Db3VudCddXSksDQogICAgICBlcnJvciA9IGZ1bmN0aW9uKGUpIHsgcmV0dXJuKDApfSkNCiAgICBpZihyZWNzID4gMjAwMCkgew0KICAgICAgZm9yKHBhZ2UgaW4gMDpmbG9vcihyZWNzLzIwMDApKXsNCiAgICAgICAgdXJsX2RhdGEgPC0gcGFzdGUwKHJlcG9fdXJsLA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgJz9wYWdlPScsIHBhZ2UsDQogICAgICAgICAgICAgICAgICAgICAgICAgICAnJnNpemU9MjAwMCcpDQogICAgICAgIHJlc3BvbnNlIDwtIHRyeUNhdGNoKA0KICAgICAgICAgIFJDdXJsOjpnZXRVUkwodXJsX2RhdGEsDQogICAgICAgICAgICAgICAgICAgICAgICAub3B0cz1saXN0KGh0dHBoZWFkZXI9aGVhZGVycykpLA0KICAgICAgICAgIGVycm9yID0gZnVuY3Rpb24oZSkgeyByZXR1cm4oTkEpIH0pDQogICAgICAgIHN1YkRhdGEgPC0gcjJkKHJlc3BvbnNlKQ0KICAgICAgICBpZihucm93KHJlc3BEYXRhKT4wKXsNCiAgICAgICAgICByZXNwRGF0YSA8LSByYmluZChyZXNwRGF0YSwgc3ViRGF0YSkNCiAgICAgICAgfSBlbHNlIHsNCiAgICAgICAgICByZXNwRGF0YSA8LSBzdWJEYXRhDQogICAgICAgIH0NCiAgICAgIH0NCiAgICB9IGVsc2Ugew0KICAgICAgcmVzcG9uc2UgPC0gdHJ5Q2F0Y2goDQogICAgICAgIFJDdXJsOjpnZXRVUkwodXJsX2RhdGEsIC5vcHRzPWxpc3QoaHR0cGhlYWRlciA9IGhlYWRlcnMpKSwNCiAgICAgICAgZXJyb3IgPSBmdW5jdGlvbihlKSB7IHJldHVybihOQSkgfSkNCiAgICAgIHJlc3BEYXRhIDwtIHIyZChyZXNwb25zZSkNCiAgICB9DQogIH0NCiAgcmVzcERhdGENCn0NCndyaXRlSXRlbSA8LSBmdW5jdGlvbihhcHAsIHJlcG9fdXJsLCBpdGVtKSB7DQogIGhlYWRlcnMgPC0gZGVmYXVsdEhlYWRlcnMoYXBwW1sndG9rZW4nXV0pDQogIGRhdGEgPC0gcmpzb246OnRvSlNPTihpdGVtKQ0KICByZXNwb25zZSA8LSB0cnlDYXRjaCgNCiAgICBSQ3VybDo6cG9zdEZvcm0ocmVwb191cmwsIC5vcHRzPWxpc3QoaHR0cGhlYWRlciA9IGhlYWRlcnMsIHBvc3RmaWVsZHMgPSBkYXRhKSksDQogICAgZXJyb3IgPSBmdW5jdGlvbihlKSB7IA0KICAgICAgcmV0dXJuKE5BKSB9KQ0KICByZXNwb25zZQ0KfQ0KdXBkYXRlSXRlbSA8LSBmdW5jdGlvbihhcHAsIHJlcG9fdXJsLCBpdGVtLCBpZCkgew0KICBoZWFkZXJzIDwtIGRlZmF1bHRIZWFkZXJzKGFwcFtbJ3Rva2VuJ11dKQ0KICBpdGVtIDwtIGMoaXRlbSwgYyhpZD1hcy5udW1lcmljKGlkKSkpDQogIGRhdGEgPC0gcmpzb246OnRvSlNPTihpdGVtKQ0KICByZXNwb25zZSA8LSB0cnlDYXRjaCgNCiAgICBSQ3VybDo6cG9zdEZvcm0ocmVwb191cmwsIC5vcHRzPWxpc3QoaHR0cGhlYWRlciA9IGhlYWRlcnMsIHBvc3RmaWVsZHMgPSBkYXRhKSksDQogICAgZXJyb3IgPSBmdW5jdGlvbihlKSB7IHJldHVybihOQSkgfSkNCiAgcmVzcG9uc2UNCn0NCmRlbGV0ZUl0ZW0gPC0gZnVuY3Rpb24oYXBwLCByZXBvX3VybCwgaWQpew0KICBoZWFkZXJzIDwtIGRlZmF1bHRIZWFkZXJzKGFwcFtbJ3Rva2VuJ11dKQ0KICBpdGVtX3VybCA8LSBwYXN0ZTAocmVwb191cmwsICcvJywgaWQpDQogIHJlc3BvbnNlIDwtIHRyeUNhdGNoKA0KICAgIGh0dHI6OkRFTEVURShpdGVtX3VybCwgYWRkX2hlYWRlcnMoaGVhZGVycykpLA0KICAgIGVycm9yID0gZnVuY3Rpb24oZSkgeyByZXR1cm4oTkEpIH0pDQogIHJlc3BvbnNlDQp9DQppbXBvcnROYWdpb3MgPC0gZnVuY3Rpb24obmFnaW9zVXJsLCBhcHAsIHJlcG8sIHJlcG9OYW1lLCBuYWdpb3NVc2VyLCBuYWdpb3NQd2Qpew0KICBjbnQgPC0gMA0KICBoZGwgPC0gUkN1cmw6OmdldFVSTChuYWdpb3NVcmwsIHVzZXJwd2Q9cGFzdGUobmFnaW9zVXNlciwgbmFnaW9zUHdkLCBzZXAgPSAnOicpLCBodHRwYXV0aCA9IDFMLCBzc2wudmVyaWZ5cGVlciA9IEZBTFNFLCBzc2wudmVyaWZ5aG9zdCA9IEZBTFNFKQ0KICBpZih0eXBlb2YoaGRsKSA9PSAnY2hhcmFjdGVyJykgew0KICAgIGlmKGpzb25saXRlOjp2YWxpZGF0ZShoZGwpKXsNCiAgICAgIHJhdyA8LSBqc29ubGl0ZTo6ZnJvbUpTT04oaGRsKQ0KICAgICAgbWV0YSA8LSByYXdbMV0kbWV0YQ0KICAgICAgcm93cyA8LSByYXdbMl0kZGF0YSRyb3cNCiAgICAgIHNlcSA8LSBhcy5pbnRlZ2VyKG1ldGEkc3RhcnQpICsNCiAgICAgICAgKDE6YXMuaW50ZWdlcihtZXRhJHJvd3MpKSphcy5pbnRlZ2VyKG1ldGEkc3RlcCkNCiAgICAgIHZhbCA8LSBsYXBwbHkocm93cyR2LCBmdW5jdGlvbih4KXsgYXMubnVtZXJpYyh4WzFdKSB9KQ0KICAgICAgZGF0YSA8LSBhcy5kYXRhLmZyYW1lKGNiaW5kKHNlcSwgdmFsKSkNCiAgICAgIGRhdGEgPC0gZGF0YS5mcmFtZShtYXRyaXgodW5saXN0KGRhdGEpLCBucm93PW5yb3coZGF0YSksIGJ5cm93PUYpKQ0KICAgICAgZGF0YSA8LSBkYXRhW2NvbXBsZXRlLmNhc2VzKGRhdGEpLCBdDQogICAgICBjb2xuYW1lcyhkYXRhKSA8LSBjKCdzZXEnLCAndmFsJykNCiAgICAgIGRhdGFfdXJsIDwtIGl0ZW1zVXJsKGFwcFtbJ3VybCddXSwgcmVwbykNCiAgICAgIHBpYV9kYXRhIDwtIHJlYWRJdGVtcyhhcHAsIGRhdGFfdXJsKQ0KICAgICAgaWYobnJvdyhkYXRhKSA+IDApIHsNCiAgICAgICAgaWYobnJvdyhwaWFfZGF0YSkgPiAwKXsNCiAgICAgICAgICBtcmdfZGF0YSA8LSBtZXJnZShkYXRhLCBwaWFfZGF0YSwgYnkueD0nc2VxJywgYnkueT0ndGltZXN0YW1wJywgYWxsID0gVFJVRSkNCiAgICAgICAgfSBlbHNlIHsNCiAgICAgICAgICBtcmdfZGF0YSA8LSBkYXRhDQogICAgICAgICAgbXJnX2RhdGEkdmFsdWUgPC0gTkENCiAgICAgICAgICBtcmdfZGF0YSRpZCA8LSBOQQ0KICAgICAgICB9DQogICAgICB9IGVsc2Ugew0KICAgICAgICBpZihucm93KHBpYV9kYXRhKSA+IDApew0KICAgICAgICAgIG1yZ19kYXRhIDwtIHBpYV9kYXRhDQogICAgICAgICAgbXJnX2RhdGEkdmFsIDwtIE5BDQogICAgICAgIH0gZWxzZSB7DQogICAgICAgICAgbXJnX2RhdGEgPC0gZGF0YS5mcmFtZSgpDQogICAgICAgIH0NCiAgICAgIH0NCiAgICAgIHVwZF9pdGVtcyA8LSBtcmdfZGF0YVsobXJnX2RhdGEkdmFsICE9IG1yZ19kYXRhJHZhbHVlKSAmICFpcy5uYShtcmdfZGF0YSRpZCksIGMoJ2lkJywgJ3NlcScsICd2YWwnKV0NCiAgICAgIHVwZF9pdGVtcyA8LSB1cGRfaXRlbXNbY29tcGxldGUuY2FzZXModXBkX2l0ZW1zKSwgXQ0KICAgICAgaWYgKG5yb3codXBkX2l0ZW1zKSA+IDApIHsNCiAgICAgICAgaW52aXNpYmxlKGFwcGx5KHVwZF9pdGVtcywgMSwgZnVuY3Rpb24oeCkgew0KICAgICAgICAgIGNudCA8LSBjbnQgKyAxDQogICAgICAgICAgaXRlbSA8LSBsaXN0KHRpbWVzdGFtcCA9IHhbWydzZXEnXV0sDQogICAgICAgICAgICAgICAgICAgICAgIHZhbHVlICAgICA9IHhbWyd2YWwnXV0pDQogICAgICAgICAgZHVtbXkgPC0gdXBkYXRlSXRlbShhcHAsIGRhdGFfdXJsLCBpdGVtLCB4W1snaWQnXV0pDQogICAgICAgIH0pKQ0KICAgICAgfQ0KICAgICAgbmV3X2l0ZW1zIDwtIG1yZ19kYXRhWyghaXMubmEobXJnX2RhdGEkdmFsKSAmIGlzLm5hKG1yZ19kYXRhJHZhbHVlKSksIGMoJ3NlcScsICd2YWwnKV0NCiAgICAgIGlmIChucm93KG5ld19pdGVtcykgPiAwKSB7DQogICAgICAgIGludmlzaWJsZShhcHBseShuZXdfaXRlbXMsIDEsIGZ1bmN0aW9uKHgpIHsNCiAgICAgICAgICBjbnQgPDwtIGNudCArIDENCiAgICAgICAgICBpdGVtIDwtIGxpc3QodGltZXN0YW1wID0geFtbJ3NlcSddXSwgdmFsdWUgPSB4W1sndmFsJ11dLCAnX295ZFJlcG9OYW1lJyA9IHJlcG9OYW1lKQ0KICAgICAgICAgIHdyaXRlSXRlbShhcHAsIGRhdGFfdXJsLCBpdGVtKQ0KICAgICAgICB9KSkNCiAgICAgIH0NCiAgICB9DQogIH0NCiAgY250DQp9DQoNCnBpYV91cmwgPC0gJ1twaWFfdXJsXScNCmFwcF9rZXkgPC0gJ1thcHBfa2V5XScNCmFwcF9zZWNyZXQgPC0gJ1thcHBfc2VjcmV0XScNCmFwcCA8LSBzZXR1cEFwcChwaWFfdXJsLCBhcHBfa2V5LCBhcHBfc2VjcmV0KQ0KdXJsIDwtIGl0ZW1zVXJsKHBpYV91cmwsICdldS5vd255b3VyZGF0YS5yb29tLm5hZ2lvcycpDQpzZW5zb3JzIDwtIHJlYWRJdGVtcyhhcHAsIHVybCkNCmZvciAoaSBpbiAxOm5yb3coc2Vuc29ycykpew0KICBpbXBvcnROYWdpb3MoYXMuY2hhcmFjdGVyKHNlbnNvcnNbaSwgJ25hZ2lvc1VybCddKSwgYXBwLCBhcy5jaGFyYWN0ZXIoc2Vuc29yc1tpLCAncmVwbyddKSwgYXMuY2hhcmFjdGVyKHNlbnNvcnNbaSwgJ25hbWUnXSksIGFzLmNoYXJhY3RlcihzZW5zb3JzW2ksICd1c2VyJ10pLCBhcy5jaGFyYWN0ZXIoc2Vuc29yc1tpLCAncGFzc3dvcmQnXSkpDQp9'
